import { useEffect, useRef, useState } from 'react';
import { ArrowRight, AudioLines, BadgeCheck, Camera, CheckCheck, ChevronRight, CircleHelp, Copy, Download, ExternalLink, Globe2, Hand, Landmark, Menu, Music2, Play, QrCode, ScanLine, ShieldCheck, Sparkles, Trophy, Volume2, VolumeX, X } from 'lucide-react';
import QRCode from 'qrcode';
import { InstrumentArt } from './components/InstrumentArt';
import { Session, type Instrument } from './components/Session';
import { getProgress, topScores } from './lib/progress';
import { instrumentIds, languages, locales, useI18n } from './i18n';
import { playNote, setSound, unlockAudio } from './lib/audio';
import { getProfile } from './lib/gestures';
export const instruments: Instrument[] = [
  { id: 'dombyra', name: 'Домбра', kazakh: 'Домбыра', category: 'Струнные', subtitle: 'Две струны. Тысяча историй.', description: 'Знакомый щипковый звук и голос казахской степи. Начни своё знакомство с музыкой с двух струн.', tag: 'Идеально для начала', color: 'sand' },
  { id: 'kobyz', name: 'Кобыз', kazakh: 'Қобыз', category: 'Струнные', subtitle: 'Голос, связывающий времена.', description: 'Смычковый инструмент с глубоким, протяжным звучанием. Открой для себя его необычный тембр.', tag: 'Глубокое звучание', color: 'sage' },
  { id: 'dauylpaz', name: 'Дауылпаз', kazakh: 'Дауылпаз', category: 'Ударные', subtitle: 'Почувствуй ритм степи.', description: 'Традиционный барабан с мощным, объёмным звуком. Создай свой ритм одним движением руки.', tag: 'Поймай ритм', color: 'rose' },
];
type Page = 'collection' | 'guide' | 'progress' | 'about';
function Mark({ small = false }: {small?: boolean}) { return <svg width={small ? 25 : 35} height={small ? 29 : 39} viewBox="0 0 36 42" fill="none" aria-hidden="true"><path d="M3 37V5l15 16L33 5v32M3 20l15 17 15-17M11 5v8m14-8v8" stroke="currentColor" strokeWidth="2.8" strokeLinecap="round" strokeLinejoin="round"/></svg>; }
function Ornament({ className = '' }: {className?: string}) { return <svg className={className} viewBox="0 0 100 100" fill="none" aria-hidden="true"><path d="M50 2v96M2 50h96M50 17C5-13 4 42 36 36C42 4-13 5 17 50M50 17C95-13 96 42 64 36C58 4 113 5 83 50M50 83C5 113 4 58 36 64C42 96-13 95 17 50M50 83C95 113 96 58 64 64C58 96 113 95 83 50" stroke="currentColor" strokeWidth="2"/></svg>; }
export default function App() {
  const { t, lang, setLang } = useI18n();
  /** Instrument display names come from the dictionaries; the Russian `name` stays the storage key. */
  const name = (id: string) => t(`inst.${id}.name`);
  const nameOf = (stored: string) => { const id = instrumentIds[stored]; return id ? name(id) : stored; };
  const [guideInstrument,setGuideInstrument]=useState('dombyra'); const guideGestures=getProfile(guideInstrument).gestures;
  const [page, setPage] = useState<Page>('collection'); const [filter, setFilter] = useState('Все инструменты');
  const [session, setSession] = useState<Instrument | null>(() => instruments.find(i=>i.id===new URLSearchParams(location.search).get('instrument')) ?? null);
  const [qr, setQr] = useState<Instrument | null>(null); const [qrImage, setQrImage] = useState(''); const [qrError, setQrError] = useState('');
  const [copied, setCopied] = useState(false); const [sound, updateSound] = useState(true); const [mobileNav, setMobileNav] = useState(false);
  const [progress, setProgress] = useState(getProgress); const [preview, setPreview] = useState<string | null>(null);
  const [boardFilter, setBoardFilter] = useState('all');
  const previewTimer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined); const previewEnd = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const copyTimer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const dialogRef = useRef<HTMLDivElement>(null);
  const realProgress = progress.filter(p=>!p.demo); const best = Math.max(0,...realProgress.map(p=>p.score));
  const board = boardFilter==='all' ? topScores(undefined,10) : topScores(instruments.find(i=>i.id===boardFilter)?.name,10);
  const url = qr ? `${location.origin}${location.pathname}?instrument=${qr.id}` : '';
  useEffect(()=> { setSound(sound); },[sound]);
  useEffect(()=> { if (!qr) return; let active = true; setQrImage(''); setQrError(''); setCopied(false); QRCode.toDataURL(url,{ width: 520, margin: 2, color: { dark: '#204b3c', light: '#ffffff' } }).then(image=>{if(active)setQrImage(image);}).catch(()=>{if(active)setQrError('qrm.err');}); return()=>{active=false;}; },[qr,url]);
  useEffect(()=> {
    if (!session && !qr) return;
    const previous = document.activeElement as HTMLElement; document.body.style.overflow='hidden';
    const first = dialogRef.current?.querySelector<HTMLElement>('button'); first?.focus();
    const handler = (e: KeyboardEvent) => {
      if(e.key==='Escape') { setSession(null);setQr(null); }
      if(e.key==='Tab') { const elements = Array.from(dialogRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input') ?? []); const first = elements[0];const last=elements.at(-1);if(e.shiftKey && document.activeElement===first){e.preventDefault();last?.focus();} else if(!e.shiftKey && document.activeElement===last){e.preventDefault();first?.focus();} }
    };
    document.addEventListener('keydown',handler); return()=>{document.body.style.overflow='';document.removeEventListener('keydown',handler);previous?.focus();};
  },[session,qr]);
  useEffect(()=>()=>{clearTimeout(previewTimer.current);clearTimeout(previewEnd.current);clearTimeout(copyTimer.current);},[]);
  function navigate(p: Page) {setPage(p);setMobileNav(false);window.scrollTo({top:0,behavior:'smooth'});}
  async function listen(i: Instrument) {clearTimeout(previewTimer.current);clearTimeout(previewEnd.current);if(preview===i.id){setPreview(null);return;}await unlockAudio().catch(()=>{});setPreview(i.id);playNote(getProfile(i.id).gestures[0].id,i.id);previewTimer.current=setTimeout(()=>playNote(getProfile(i.id).gestures[1].id,i.id),450);previewEnd.current=setTimeout(()=>setPreview(null),1800);}
  const nav = ([['collection',Music2],['guide',ScanLine],['progress',Trophy],['about',Landmark]] as const).map(([id,icon])=>({id:id as Page,icon,label:t(`nav.${id}`)}));
  return <div className="app-shell">
    <aside className={`sidebar ${mobileNav?'mobile-open':''}`}><a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('collection');}}><Mark/><div>MURA<span>{t('side.tag')}</span></div></a><span className="nav-caption">{t('side.caption')}</span><nav>{nav.map(item=><button key={item.id} className={page===item.id?'active':''} onClick={()=>navigate(item.id)}><item.icon size={19}/>{item.label}{page===item.id&&<span className="nav-dot"/>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="sidebar-invitation"><Ornament/><span>{t('side.inv1')}</span><p>{t('side.inv2')}</p><span className="invitation-line"/></div><div className="sidebar-footer"><span>{t('side.made')}</span><span className="kz-mark">KZ <span>✦</span></span></div></div>
    </aside>
    <main className="main"><header className="topbar"><button className="icon-button mobile-menu" onClick={()=>setMobileNav(!mobileNav)} aria-label={t('nav.menu')}>{mobileNav?<X/>:<Menu/>}</button><div className="breadcrumb">{t('top.museum')} <ChevronRight size={14}/><span>{nav.find(n=>n.id===page)?.label}</span></div><div className="topbar-actions"><span className="online-label"><span className="live-dot"/> {t('top.open')}</span><span className="topbar-divider"/><button className="sound-button" onClick={()=>updateSound(!sound)} aria-label={sound?t('sound.off'):t('sound.on')} title={sound?t('sound.off'):t('sound.on')}>{sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</button><span className="lang-switch" role="group" aria-label={t('lang.aria')}>{languages.map(l=><button key={l.id} aria-pressed={lang===l.id} lang={l.id} title={l.name} onClick={()=>setLang(l.id)}>{l.label}</button>)}</span></div></header>
    <div className="page-content">
    {page==='collection' && <>
      <div className="page-heading"><div><span className="eyebrow">{t('home.eyebrow')}</span><h1>{t('hero.title')}</h1><p>{t('hero.lead')}</p></div><div className="edition"><Ornament/><span>{t('home.edition1')}<br/>{t('home.edition2')}</span></div></div>
      <div className="hero-grid"><section className="hero"><div className="hero-text"><div className="hero-badge"><span className="live-dot"/> {t('home.badge')}</div><h2>{t('home.h1')}<br/>{t('home.h2')}<br/><em>{t('home.h3')}</em></h2><p>{t('home.text1')}<br/>{t('home.text2')}</p><button className="button light" onClick={()=>setSession(instruments[0])}>{t('hero.cta')} <ArrowRight size={18}/></button><span className="hero-footnote"><Camera size={14}/> {t('home.footnote')}</span></div><div className="hero-art"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit orbit-three"/><Ornament className="hero-ornament"/><InstrumentArt/><span className="hero-art-label"><span>01 / {t('inst.dombyra.alt')}</span>{t('home.artLabel')}</span><div className="sound-wave">{Array.from({length:17},(_,i)=><i key={i} style={{height:`${8+Math.sin(i*.9)**2*26}px`}}/>)}</div></div></section>
      <section className="journey-card"><div className="journey-top"><span className="journey-icon"><Sparkles size={21}/></span><span>{t('journey.eyebrow')}</span></div><h3>{t('journey.title1')}<br/>{t('journey.title2')}</h3><p>{t('journey.lead1')}<br/>{t('journey.lead2')}</p><div className="journey-steps"><div><span>01</span><p><b>{t('steps.1.t')}</b><small>{t('journey.1.d')}</small></p></div><div><span>02</span><p><b>{t('journey.2.t')}</b><small>{t('journey.2.d')}</small></p></div><div><span>03</span><p><b>{t('journey.3.t')}</b><small>{t('journey.3.d')}</small></p></div></div><button className="journey-link" onClick={()=>navigate('guide')}>{t('journey.link')} <ArrowRight size={17}/></button></section></div>
      <section className="collection-section"><div className="section-heading"><div><h2>{t('coll.title')} <span>03</span></h2><p>{t('coll.lead')}</p></div><div className="filters" role="group" aria-label={t('filter.aria')}>{([['Все инструменты','filter.all'],['Струнные','filter.strings'],['Ударные','filter.drums']] as const).map(([value,key])=><button key={value} onClick={()=>setFilter(value)} className={filter===value?'selected':''} aria-pressed={filter===value}>{t(key)}</button>)}</div></div>
      <div className="instrument-grid">{instruments.filter(i=>filter==='Все инструменты'||i.category===filter).map((i,n)=><article className="instrument-card" key={i.id}><div className={`card-art ${i.color}`}><div className="art-top"><span className="category-label">{i.category==='Струнные'?<AudioLines size={13}/>:<Music2 size={13}/>} {t(i.category==='Струнные'?'filter.strings':'filter.drums')}</span><button className="qr-button" onClick={()=>setQr(i)} aria-label={t('card.qr',{name:name(i.id)})} title={t('card.qrTitle')}><QrCode size={18}/></button></div><span className="card-watermark">{t(`inst.${i.id}.alt`)}</span><InstrumentArt type={i.id}/><span className="instrument-number">0{instruments.indexOf(i)+1}</span><button className={`listen-button ${preview===i.id?'is-playing':''}`} disabled={!sound} onClick={()=>void listen(i)} aria-label={t('card.listen',{name:name(i.id)})} title={sound?t('card.listenTitle'):t('card.listenOff')}>{preview===i.id?<AudioLines size={16}/>:<Play size={14} fill="currentColor"/>}</button></div><div className="card-content"><div className="instrument-heading"><h3>{name(i.id)}</h3><span>{t(`inst.${i.id}.alt`)}</span></div><p>{t(`inst.${i.id}.sub`)}</p><div className="card-bottom"><span className={`instrument-tag ${n===0?'beginner':''}`}>{i.id==='dombyra'?<Sparkles size={12}/>:<AudioLines size={12}/>} {t(`inst.${i.id}.tag`)}</span><button className="play-instrument" onClick={()=>setSession(i)}>{t('card.play')} <ArrowRight size={16}/></button></div></div></article>)}</div></section>
      <section className="museum-banner"><div className="qr-illustration"><QrCode size={36}/><span className="scan-corner"/></div><div><span className="eyebrow">{t('banner.eyebrow')}</span><h3>{t('qr.banner')}</h3><p>{t('banner.text')}</p></div><button className="banner-link" onClick={()=>setQr(instruments[0])}>{t('qr.try')} <ArrowRight size={17}/></button><Ornament className="banner-ornament"/></section>
      <div className="trust-row"><span><ShieldCheck size={15}/> {t('trust.1')}</span><span><Hand size={15}/> {t('trust.2')}</span><span><Globe2 size={15}/> {t('trust.3')}</span></div>
    </>}
    {page==='guide' && <><div className="page-heading"><div><span className="eyebrow">{t('guide.eyebrow')}</span><h1>{t('guide.title')}</h1><p>{t('guide.lead')}</p></div><Hand className="page-heading-icon" size={54}/></div><div className="guide-banner"><div><span className="eyebrow">{t('guide.b.eyebrow')}</span><h2>{t('guide.b.t1')}<br/>{t('guide.b.t2')}</h2><p>{t('guide.b.text')}</p><button className="button light" onClick={()=>setSession(instruments[0])}>{t('guide.b.cta')} <ArrowRight size={18}/></button></div><ScanLine size={130} strokeWidth={.8}/></div><div className="guide-instrument-picker" role="group" aria-label={t('guide.tabs')}>{instruments.map(i=><button key={i.id} className={guideInstrument===i.id?'selected':''} aria-pressed={guideInstrument===i.id} onClick={()=>setGuideInstrument(i.id)}>{name(i.id)}</button>)}</div><div className="guide-grid">{guideGestures.map((g,i)=><article key={g.id} className="guide-card"><span className="eyebrow">{t('guide.move')} 0{i+1}</span><span className="big-gesture technique-symbol">{g.symbol}</span><h3>{t(`g.${g.id}.name`)}</h3><span className="pill">{t(`g.${g.id}.action`)}</span><p>{t(`g.${g.id}.instruction`)}</p></article>)}</div><div className="guide-ar-note"><ScanLine size={24}/><span><b>{t('guide.arNote.b')}</b> {t('guide.arNote')}</span></div><div className="explanation-grid"><section className="content-panel"><div className="panel-icon"><CircleHelp/></div><h3>{t('guide.h1')}</h3><p>{t('guide.p1')}</p><blockquote>{t('guide.quote')}</blockquote><p>{t('guide.p2b')}</p></section><section className="content-panel"><div className="panel-icon"><Trophy/></div><h3>{t('guide.h2')}</h3><p>{t('guide.p3')}</p><p>{t('guide.p4')}</p><button className="text-button" onClick={()=>navigate('progress')}>{t('guide.link')} <ArrowRight size={16}/></button></section></div></>}
    {page==='progress' && <><div className="page-heading"><div><span className="eyebrow">{t('progress.eyebrow')}</span><h1>{t('progress.title')}</h1><p>{t('progress.lead')}</p></div><Trophy className="page-heading-icon" size={54}/></div><div className="progress-stats"><article><span className="panel-icon"><Trophy/></span><strong>{best}</strong><span>{t('stat.best')}</span></article><article><span className="panel-icon"><Music2/></span><strong>{realProgress.length}</strong><span>{t('stat.count')}</span></article><article><span className="panel-icon"><BadgeCheck/></span><strong>{new Set(realProgress.map(p=>p.instrument)).size}<small> / 3</small></strong><span>{t('stat.open')}</span></article></div><section className="content-panel"><h2>{t('board.title')}</h2><div className="guide-instrument-picker" role="group" aria-label={t('board.aria')}><button className={boardFilter==='all'?'selected':''} aria-pressed={boardFilter==='all'} onClick={()=>setBoardFilter('all')}>{t('board.all')}</button>{instruments.map(i=><button key={i.id} className={boardFilter===i.id?'selected':''} aria-pressed={boardFilter===i.id} onClick={()=>setBoardFilter(i.id)}>{name(i.id)}</button>)}</div>{board.length ? <ol className="rank-list">{board.map((p,i)=><li className="rank-row" key={p.id}><span className="rank-n">{i+1}</span><span><b>{nameOf(p.instrument)}</b><small>{t('board.row',{d:new Date(p.date).toLocaleDateString(locales[lang],{day:'numeric',month:'long'}),n:p.notes})}</small></span><strong>{p.score}</strong></li>)}</ol> : <p className="lead">{t('board.empty')}</p>}</section>{progress.length ? <section className="content-panel history"><h2>{t('hist.title')}</h2>{progress.map(p=><div className="history-row" key={p.id}><span className="history-icon"><Music2 size={22}/></span><div><b>{nameOf(p.instrument)}</b><small>{new Date(p.date).toLocaleString(locales[lang],{day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'})} · {p.demo?t('hist.demo'):t('hist.camera')}</small></div><span>{t('hist.moves',{n:p.notes})}</span><strong>{p.score} <small>{t('hist.points')}</small></strong></div>)}</section> : <section className="empty-state"><div className="empty-art"><Ornament/><Music2 size={40}/></div><h2>{t('empty.title')}</h2><p>{t('empty.text')}</p><button className="button primary" onClick={()=>navigate('collection')}>{t('empty.cta')} <ArrowRight size={17}/></button></section>}<p className="storage-note"><ShieldCheck size={15}/> {t('storage.note')}</p></>}
    {page==='about' && <><div className="page-heading"><div><span className="eyebrow">{t('about.eyebrow')}</span><h1>{t('about.title')}</h1><p>{t('about.lead')}</p></div></div><section className="about-hero"><Ornament/><span className="eyebrow">{t('about.hero.eyebrow')}</span><h2>{t('about.hero.t1')}<br/>{t('about.hero.t2')}<br/><em>{t('about.hero.t3')}</em></h2><p>{t('about.lead')}</p></section><div className="explanation-grid"><section className="content-panel"><Landmark className="panel-icon"/><h3>{t('about.h1')}</h3>{instruments.map(i=><div className="about-instrument" key={i.id}><b>{name(i.id)} · {t(`inst.${i.id}.alt`)}</b><p>{t(`inst.${i.id}.desc`)}</p></div>)}</section><section className="content-panel"><Camera className="panel-icon"/><h3>{t('about.h2')}</h3><p>{t('about.p1')}</p><p>{t('about.p2')}</p><a className="text-button" href="https://ai.google.dev/edge/mediapipe/solutions/vision/hand_landmarker/web_js" target="_blank" rel="noreferrer">{t('about.link')} <ExternalLink size={14}/></a></section></div></>}
    <footer className="page-footer"><span>© {new Date().getFullYear()} {t('footer.copy')}</span><span>{t('footer.tag')} <span>✦</span></span></footer>
    </div></main>
    {(session || qr) && <div ref={dialogRef}>{session && <Session key={session.id} instrument={session} close={()=>{setSession(null);if(location.search)history.replaceState(null,'',location.pathname);}} onComplete={()=>setProgress(getProgress())} sound={sound} toggleSound={()=>updateSound(s=>!s)}/>} {qr && <div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)setQr(null);}}><section className="qr-modal" role="dialog" aria-modal="true" aria-labelledby="qr-title"><div className="modal-header"><span className="eyebrow">{t('qrm.label')}</span><button className="icon-button" aria-label={t('qrm.close')} onClick={()=>setQr(null)}><X size={21}/></button></div><div className="qr-title-icon"><QrCode size={27}/></div><h2 id="qr-title">{t('qrm.title',{name:name(qr.id)})}</h2><div className="qr-image">{qrImage ? <img src={qrImage} alt={t('qrm.alt',{name:name(qr.id)})}/> : <p>{qrError ? t(qrError) : t('qrm.creating')}</p>}</div>{['localhost','127.0.0.1'].includes(location.hostname) && <p className="qr-local-note">{t('qrm.local')}</p>}<div className="qr-actions"><button className="button primary" onClick={()=>{void navigator.clipboard.writeText(url).then(()=>{setCopied(true);clearTimeout(copyTimer.current);copyTimer.current=setTimeout(()=>setCopied(false),2500);}).catch(()=>setQrError('qrm.copyErr'));}}>{copied?<CheckCheck size={16}/>:<Copy size={16}/>} {copied?t('qrm.copied'):t('qrm.copy')}</button>{qrImage && <a className="button secondary" href={qrImage} download={`mura-${qr.id}-qr.png`}><Download size={16}/> {t('qrm.download')}</a>}</div>{qrError&&<p role="status">{t(qrError)}</p>}<input className="qr-url" value={url} readOnly aria-label={t('qrm.url')} onFocus={e=>e.target.select()}/></section></div>}</div>}
  </div>;
}
